Feature/add CWE endpoint backend
caverav/auditforge pull request #104
Opened 2024-09-23 02:36 UTC by iTzGooDLife

## Descripción

Actualmente se tiene hardcodeado el endpoint `/classify` (recomendación de cwe) en el frontend, donde se accede directamente a la API del modelo. 
Cambios realizados:
* Se agrega el endpoint `/classify` al backend con sus permisos respectivos.
* Ya no se expone el puerto 8000 del contenedor `auditforge-cwe-api`.
* Se crea una nueva red llamada `cwe-api`, configurada para que solo el contenedor del Backend tenga acceso a la API.

## Motivación y Contexto

El objetivo es permitir el acceso al modelo únicamente a través del backend, garantizando que solo se puedan realizar consultas si el usuario está autorizado.

## ¿Cómo ha sido probado?

Se realizan consultas al modelo mediante las funcionalidades añadir o editar vulnerabilidad usando usuarios con diferentes roles. Además, se debería probar hacer consultas desde contenedores fuera de la red creada (mongo o auditforge-frontend) usando curl o similar.

## Capturas de pantalla (si es apropiado):

## Tipos de cambios

- [ ] Bugfix (cambio que no interrumpe el funcionamiento y que soluciona un problema)
- [X] New feature (cambio que no interrumpe el funcionamiento y que añade funcionalidad)
- [ ] Breaking change (corrección o funcionalidad que podría causar que la funcionalidad existente cambie)

## Lista de verificación:

- [X] Mi código sigue el estilo de código de este proyecto.
- [ ] Mi cambio requiere una modificación en la documentación.
- [ ] He actualizado la documentación en consecuencia.
- [ ] Requiere nuevos tests.

2024-09-23 02:52 UTC, caverav commented on docker-compose.yml
> +    driver: bridge
la verdad sí considero que es un mejor nombre, pero no es necesario

2024-09-23 02:54 UTC, caverav commented on backend/src/routes/cwe.js
> +
Estaría bien algo así

2024-09-23 02:56 UTC, caverav commented on backend/src/routes/cwe.js
> +      }
Yep, tiene razón el bot

2024-09-23 02:56 UTC, iTzGooDLife commented on backend/src/routes/cwe.js
> +
> Estaría bien algo así

Lo revisé y considero que lo único necesario de esta sugerencia es "typeof req.body.vuln !== 'string'. Quizás se podría mejorar lo 2do mencionado, pero no implementar directamente, ya que el .trim no viene a este caso.

2024-09-23 02:58 UTC, caverav commented on backend/src/routes/cwe.js
> +
el trim sí es útil, para no mandar tokens innecesarios al modelo

2024-09-23 02:58 UTC, iTzGooDLife commented on docker-compose.yml
> +    driver: bridge
Estoy de acuerdo en que sería un buen nombre, pero se implementó así inicialmente porque no se identificó un formato con la red utilizada actualmente (backend).

2024-09-23 02:59 UTC, caverav commented on backend/src/routes/cwe.js
> +
Pero sí separarlo, cosa que no tire error

2024-09-23 03:02 UTC, caverav requested changes

2024-09-23 03:02 UTC, caverav commented on backend/src/routes/cwe.js
> +          throw networkError;
De dónde sacas esta variable? Debes definirla antes de usarla

2024-09-23 03:06 UTC, caverav requested changes

2024-09-23 03:06 UTC, caverav commented on backend/src/routes/cwe.js
> +        throw error;
Qué utilidad tiene lanzar un error al atraparlo?

2024-09-23 03:06 UTC, caverav commented on backend/src/routes/cwe.js
> +          throw networkError;
Lo mismo, se lanza un error al alcanzarlo

2024-09-24 00:00 UTC, caverav commented on backend/src/routes/cwe.js
> +        );
En teoría en el contenedor está bien porque ocupa node con major 20, pero es verdad que es desde la 18 que soporta fetch nativamente, de hecho es una feat experimental

2024-09-24 00:21 UTC, caverav commented on backend/src/routes/cwe.js
> +  let acl = require('../lib/auth').acl;
Yep

2024-09-24 00:29 UTC, caverav requested changes

2024-09-24 00:29 UTC, caverav commented on backend/src/app.js
> +global.cweConfig = require('./config/config-cwe.json')['cwe-container'];
Por qué declararlo como global si puedes utilizarlo en `cwe.js` y así también es amigable con los LSP, ya que el uso de cweConfig como variable no tiene declaración propia dentro de `cwe.js`

2024-09-24 00:30 UTC, caverav submitted a review, later dismissed
Ojo, no pusiste que se deben hacer cambios a la documentación, esta funcionalidad sí requiere cambios en la documentación, y no está indicado ni realizado

2024-09-24 00:39 UTC, iTzGooDLife commented on backend/src/app.js
> +global.cweConfig = require('./config/config-cwe.json')['cwe-container'];
Lo declaré globalmente por si se tenia que hacer uso de esa data en otro archivo en el futuro, asi no tener que llamar al archivo de configuración que contiene esas variables multiples veces, lo que consideré que sería más eficiente. Si esto realmente no es así o es mejor modificarlo, se puede hacer sin problema.

2024-09-24 00:40 UTC, iTzGooDLife commented
> Ojo, no pusiste que se deben hacer cambios a la documentación, esta funcionalidad sí requiere cambios en la documentación, y no está indicado ni realizado

true. Se debe modificar la documentación sobre la configuración de cwe en el backend, modificaré el PR y la documentación. Si detectaste otro cambio que requiera documentación, por favor indicar.

2024-09-24 01:50 UTC, caverav commented
Otro detalle es que se están haciendo consultas por `http`, hay que actualizar la API de la clasificación para que ocupe TLS (idealmente 1.3 y 1.2, no menos)

2024-09-24 02:59 UTC, iTzGooDLife commented
> Otro detalle es que se están haciendo consultas por `http`, hay que actualizar la API de la clasificación para que ocupe TLS (idealmente 1.3 y 1.2, no menos)

Sí, es verdad que se debe ocupar un protocolo seguro para la comunicación con la API del modelo, pero estoy en duda si entraría dentro del scope de este PR.

2024-09-24 13:00 UTC, caverav commented
> > Otro detalle es que se están haciendo consultas por `http`, hay que actualizar la API de la clasificación para que ocupe TLS (idealmente 1.3 y 1.2, no menos)
> 
> Sí, es verdad que se debe ocupar un protocolo seguro para la comunicación con la API del modelo, pero estoy en duda si entraría dentro del scope de este PR.

Si el PR se trata sobre añadir el endpoint de CWE al backend, sí entra, ya que hay que hacerlo de forma segura, ahora, obviamente se puede dejar como issue pendiente y hacerlo en otro PR

2024-10-01 22:21 UTC, jllanosg commented
@iTzGooDLife cual es el estado de este PR? Aún veo comentarios sin resolver

2024-10-01 22:52 UTC, iTzGooDLife commented
> @iTzGooDLife cual es el estado de este PR? Aún veo comentarios sin resolver

El PR se encuentra finalizado, si los comentarios de coderabbit a los que te refieres eran los de la documentación, esto ya se encuentra listo. @jllanosg

2024-10-05 16:01 UTC, Sealra approved these changes
LGTM 👍

2024-10-07 17:35 UTC, jllanosg approved these changes
OK. Intenté hacer ping desde el container del backend y no tuve problemas, distinto a cuando lo hice desde el container del front; por lo que el aislamiento aparentemente funciona bien.

2024-10-07 17:38 UTC, merged