✨ feat: Add functionality to add new findings in audits
caverav/auditforge pull request #128
Opened 2024-10-08 22:08 UTC by caverav

## Descripción

Agrega funcionalidad de añadir hallazgos a una auditoría mediante la vulnerabilidades ya existentes o crear una nueva

## Motivación y Contexto

Para poder gestionar correctamente hallazgos de una auditoría

## ¿Cómo ha sido probado?

Haciendo click en el símbolo + en la tabla de vulnerabilidades y añadir una vulnerabilidad nueva

## Tipos de cambios

- [ ] Bugfix (cambio que no interrumpe el funcionamiento y que soluciona un problema)
- [x] New feature (cambio que no interrumpe el funcionamiento y que añade funcionalidad)
- [ ] Breaking change (corrección o funcionalidad que podría causar que la funcionalidad existente cambie)

## Lista de verificación:

- [x] Mi código sigue el estilo de código de este proyecto.
- [ ] Mi cambio requiere una modificación en la documentación.
- [ ] He actualizado la documentación en consecuencia.
- [x] Requiere nuevos tests.

2024-10-08 22:12 UTC, jllanosg commented
![imagen](https://github.com/user-attachments/assets/963d8683-5386-469e-9baa-c20166ad8c6b)

que pasa con esto?

2024-10-08 22:58 UTC, massi-ponce approved these changes
LGTM

2024-10-09 18:21 UTC, iTzGooDLife commented
Consulta, al agregar un finding, este deberia aparecer a la izquierda cierto? o no está contemplado?

![image](https://github.com/user-attachments/assets/d6523eef-bb85-4f1c-8972-a36648e07e7d)

2024-10-09 18:24 UTC, iTzGooDLife requested changes
Al agregar una vulnerabilidad el sidebar no se actualiza hasta que sales y vuelves a entrar a al auditoria, lo cual no parece el funcionamiento correcto, ya que se debería refrescar sin la necesidad de salir.

![image](https://github.com/user-attachments/assets/d6523eef-bb85-4f1c-8972-a36648e07e7d)

2024-10-09 19:07 UTC, caverav commented
> Al agregar una vulnerabilidad el sidebar no se actualiza hasta que sales y vuelves a entrar a al auditoria, lo cual no parece el funcionamiento correcto, ya que se debería refrescar sin la necesidad de salir.
> 
> Agregando findings:
> ![image](https://github.com/user-attachments/assets/d6523eef-bb85-4f1c-8972-a36648e07e7d)
> 
> 
> Luego de salir y entrar del audit:
> ![image](https://github.com/user-attachments/assets/33fc8649-5d3e-4d4f-ba33-ede24fe7708c)
> 

Sí, eso es un pendiente pero no creo conveniente incluirlo en el PR, ya que al no ser hijo un componente del otro, no se pueden pasar estados fácilmente, así que se debe dejar pendiente como issue

2024-10-09 19:11 UTC, iTzGooDLife requested changes

2024-10-09 19:11 UTC, iTzGooDLife commented on frontend/src/services/audits.ts
> +        customFields: data.details[0].customFields,
Al utilizar data.details[0] se limita a los detalles del primer lenguaje del hallazgo, aunque haya un lenguaje secundario este no será considerado. Se propone utilizar un nuevo parámetro para la función y luego filtrar los details en base a ese parámetro.

2024-10-10 15:09 UTC, caverav commented on frontend/src/services/audits.ts
> +        customFields: data.details[0].customFields,
Gracias por la acotación, ya está solucionado

2024-10-10 20:48 UTC, jllanosg requested changes
La funcionalidad está OK; solamente cambiar el font weight para mejorar el contrase.

2024-10-10 20:48 UTC, jllanosg commented on frontend/src/components/navbar/AuditSidebar.tsx
> +          <div className={clsx('mb-4 font-thin', isCollapsed && 'sr-only')}>
```suggestion
          <div className={clsx('mb-4 font-light', isCollapsed && 'sr-only')}>
```

Este cambio mejora el contraste, ya que con font-thin no parece que la letra fuera de un color claro.

2024-10-11 01:31 UTC, Sealra commented
![image](https://github.com/user-attachments/assets/ee400ff8-e780-4d4c-8df4-809720caf3f2)

Permite agregar indefinidamente el mismo audit, ¿esto es un comportamiento esperado?

2024-10-11 01:36 UTC, caverav commented
> ![image](https://private-user-images.githubusercontent.com/71726988/375594480-ee400ff8-e780-4d4c-8df4-809720caf3f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2MTA4NzksIm5iZiI6MTcyODYxMDU3OSwicGF0aCI6Ii83MTcyNjk4OC8zNzU1OTQ0ODAtZWU0MDBmZjgtZTc4MC00ZDRjLThkZjQtODA5NzIwY2FmM2YyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDAxMzYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1MDE3MjU2Y2E2NzM5NTQ0ZTgyZTdjODdhMjU1ZTkwOGE1YzYzOWNjZmJmN2NiMzRkZTEyMGU2NDBmOWE1OGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.K_c6czlRshxuDr6_jw1mSuOs4T3hDXpyNIA5NjO4LGU)
> 
> Permite agregar indefinidamente el mismo audit, ¿esto es un comportamiento esperado?

Sí

2024-10-11 01:53 UTC, Sealra commented
![image](https://github.com/user-attachments/assets/7c17a811-91ab-480e-bfbd-aec913657d31)

Si _title_ esta vacío no muestra ningún toast de por qué no pasa nada (porque retorna error).
![image](https://github.com/user-attachments/assets/99da6a55-1b23-4b72-9527-7d54dbaa3d5a)

Al ingresar a la vista, este dropdown inicia vacío, queda algo raro como UI y creo que debería venir ya con una opción.
![image](https://github.com/user-attachments/assets/0399b0cc-2f5c-4ef4-a118-8236b6be51bb)

2024-10-11 21:08 UTC, iTzGooDLife commented
LGTM, aprobaré luego de que @massi-ponce haga implementación de los campos faltantes al agregar findings.

2024-10-11 22:17 UTC, iTzGooDLife requested changes

2024-10-11 22:17 UTC, iTzGooDLife commented on frontend/src/services/audits.ts
> +        cvssv3: data.cvssv3,
Falta el prop category, donde este puede ser string o null. Originalmente este sirve para filtrar por categoria.

2024-10-12 20:53 UTC, massi-ponce commented on frontend/src/services/audits.ts
> +        cvssv3: data.cvssv3,
Yo creo que esperaré que se resuelva esto y daré por aprobado este PR.

2024-10-13 22:18 UTC, Icksir commented
> Al agregar una vulnerabilidad el sidebar no se actualiza hasta que sales y vuelves a entrar a al auditoria, lo cual no parece el funcionamiento correcto, ya que se debería refrescar sin la necesidad de salir.
> 
> Agregando findings: ![image](https://private-user-images.githubusercontent.com/66756239/375085281-d6523eef-bb85-4f1c-8972-a36648e07e7d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4NTcwNzMsIm5iZiI6MTcyODg1Njc3MywicGF0aCI6Ii82Njc1NjIzOS8zNzUwODUyODEtZDY1MjNlZWYtYmI4NS00ZjFjLTg5NzItYTM2NjQ4ZTA3ZTdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEzVDIxNTkzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwMmZlZDYxZGQ1YmRkN2E1NTgzZDMyY2FiMjg0ZjQ3MjdiZTU3NWY3ODViZmYzMzhkNThiMjExODE1MjQ4YzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.IV9hu0Jlc99mBf05AlIqwVo9yXmOKDNuoSiQIBPCXSs)
> 
> Luego de salir y entrar del audit: ![image](https://private-user-images.githubusercontent.com/66756239/375086612-33fc8649-5d3e-4d4f-ba33-ede24fe7708c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4NTcwNzMsIm5iZiI6MTcyODg1Njc3MywicGF0aCI6Ii82Njc1NjIzOS8zNzUwODY2MTItMzNmYzg2NDktNWQzZS00ZDRmLWJhMzMtZWRlMjRmZTc3MDhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEzVDIxNTkzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlMjQ5YWU4YjBlNzg3NTA1YjZhNjcxZmYxODAzNmMyMzIyYWEwYWFkNmU3NjdjMTRhZGU3NDA0MzA0YTU3MmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4-go265sT8mZq5tSpTvGtsoFAWYX-9mtNQH99FoEnI0)

Pienso esto mismo, los cambios siento que deberían visualizarse sin refrescar la página

2024-10-14 00:38 UTC, jllanosg commented
> > Al agregar una vulnerabilidad el sidebar no se actualiza hasta que sales y vuelves a entrar a al auditoria, lo cual no parece el funcionamiento correcto, ya que se debería refrescar sin la necesidad de salir.
> > Agregando findings: ![image](https://private-user-images.githubusercontent.com/66756239/375085281-d6523eef-bb85-4f1c-8972-a36648e07e7d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4NTcwNzMsIm5iZiI6MTcyODg1Njc3MywicGF0aCI6Ii82Njc1NjIzOS8zNzUwODUyODEtZDY1MjNlZWYtYmI4NS00ZjFjLTg5NzItYTM2NjQ4ZTA3ZTdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEzVDIxNTkzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwMmZlZDYxZGQ1YmRkN2E1NTgzZDMyY2FiMjg0ZjQ3MjdiZTU3NWY3ODViZmYzMzhkNThiMjExODE1MjQ4YzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.IV9hu0Jlc99mBf05AlIqwVo9yXmOKDNuoSiQIBPCXSs)
> > Luego de salir y entrar del audit: ![image](https://private-user-images.githubusercontent.com/66756239/375086612-33fc8649-5d3e-4d4f-ba33-ede24fe7708c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4NTcwNzMsIm5iZiI6MTcyODg1Njc3MywicGF0aCI6Ii82Njc1NjIzOS8zNzUwODY2MTItMzNmYzg2NDktNWQzZS00ZDRmLWJhMzMtZWRlMjRmZTc3MDhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEzVDIxNTkzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlMjQ5YWU4YjBlNzg3NTA1YjZhNjcxZmYxODAzNmMyMzIyYWEwYWFkNmU3NjdjMTRhZGU3NDA0MzA0YTU3MmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4-go265sT8mZq5tSpTvGtsoFAWYX-9mtNQH99FoEnI0)
> 
> Pienso esto mismo, los cambios siento que deberían visualizarse sin refrescar la página

esto ya fue respondido si no me equivoco, y es que se escapa del scope del pr; son componentes separados y es más dificil hacer la actualización

2024-10-14 16:06 UTC, massi-ponce approved these changes
LGTM

2024-10-15 01:37 UTC, iTzGooDLife approved these changes
LGTM. Por favor al mergear hacer el issue para el refresco de los findings al momento de ser agregadas.

2024-10-15 02:46 UTC, jllanosg approved these changes
gut

2024-10-15 02:46 UTC, merged