feat: added customSections on audits
caverav/auditforge pull request #146
Opened 2024-10-14 01:12 UTC by Sealra

## Descripción

Se agregan vistas para la edición de customSections en audits.

## Motivación y Contexto

Permite la modificación específica para cada audit de los customSections (asociados a uno o varios customField)

## ¿Cómo ha sido probado?

_npm run build_
A través de la misma vista, editando cada campo.

## Capturas de pantalla (si es apropiado):

## Tipos de cambios

- [ ] Bugfix (cambio que no interrumpe el funcionamiento y que soluciona un problema)
- [ X ] New feature (cambio que no interrumpe el funcionamiento y que añade funcionalidad)
- [ ] Breaking change (corrección o funcionalidad que podría causar que la funcionalidad existente cambie)

## Lista de verificación:

- [ X ] Mi código sigue el estilo de código de este proyecto.
- [ ] Mi cambio requiere una modificación en la documentación.
- [ ] He actualizado la documentación en consecuencia.
- [ ] Requiere nuevos tests.

2024-10-14 01:22 UTC, Sealra commented on frontend/src/services/data.ts
> +};
Los Section puede venir sin ícono (como response del back)

2024-10-14 01:22 UTC, Sealra commented on frontend/src/main.tsx
> +          },
No entiendo a qué se refiere, si está funcionando correctamente :sectionId

2024-10-14 01:22 UTC, Sealra commented on frontend/src/routes/audits/index.tsx
> +import { Sections } from './edit/sections/sections';
Es literalmente lo mismo XD

2024-10-14 01:25 UTC, Sealra commented on frontend/src/routes/audits/edit/sections/sections.tsx
> +  const [dataAuditSection, setDataAuditSection] = useState<AuditSectionById>();
Creo que no tiene relevancia, además, ListItem no permite null

2024-10-14 01:26 UTC, Sealra commented on frontend/src/routes/audits/edit/sections/sections.tsx
> +    } catch (error) {
No sé realmente como se podría resolver esto, un if previo? creo que en caso de error daria el mismo resultado.

2024-10-14 01:26 UTC, caverav commented on frontend/src/routes/audits/edit/sections/sections.tsx
> +  const [dataAuditSection, setDataAuditSection] = useState<AuditSectionById>();
Sí tiene relevancia, y justamente no permite null, por lo que será undefined (que es peor), así que el tipo  debería ser ListItem | null

2024-10-14 01:30 UTC, Sealra commented on frontend/src/routes/audits/edit/sections/sections.tsx
> +    }
Buena acotación, en un principio se realizó para evitar una consulta que se repetia indefinidamente.

2024-10-14 01:32 UTC, Sealra commented on frontend/src/routes/audits/edit/sections/sections.tsx
> +  };
Buena acotación

2024-10-14 01:34 UTC, Sealra commented on frontend/src/routes/audits/edit/sections/sections.tsx
> +            : textValues;
Corregido

2024-10-14 01:35 UTC, Sealra commented on frontend/src/routes/audits/edit/AuditRoot.tsx
> +          })),
Es cierto, no me estaba dando problemas porque definía ambos campos igual, corregido.

2024-10-14 01:36 UTC, Sealra commented on frontend/src/routes/audits/edit/AuditRoot.tsx
> +  }, [auditId, sections]);
Esto puede ser un issue, prioricé la funcionalida por tiempo.

2024-10-14 01:38 UTC, Sealra commented on frontend/src/routes/audits/edit/sections/AuditCustomFields.tsx
> +  setCurrentCustomFields: (fields: any) => void;
Esto es un issue definitivamente, tuve que realizarlo así porque si no se requeriría la refactorización de los componentes de _Custom Fields_, debido a los tipos de dato que acepta.

2024-10-14 01:38 UTC, Sealra commented on frontend/src/routes/audits/edit/sections/AuditCustomFields.tsx
> +  setCurrentCustomFields: (fields: any) => void;
Y claramente por temas de tiempo esto no era/es viable.

2024-10-14 01:40 UTC, Sealra commented on frontend/src/routes/audits/edit/sections/AuditCustomFields.tsx
> +  };
Al solo considerar el idioma propio del Audit, es innecesario considerar para más de un idioma, esto también es debido a la reutilización de código y componentes de _Custom Fields_

2024-10-14 01:40 UTC, Sealra commented on frontend/src/routes/audits/edit/sections/AuditCustomFields.tsx
> +                    );
Son props obligatorios de RichText, modificarlos va fuera del scope de este pr.

2024-10-14 01:41 UTC, Sealra commented on frontend/src/routes/audits/edit/sections/AuditCustomFields.tsx
> +                }
Reutilización de código de _Custom Fields_ y sirve.

2024-10-14 01:42 UTC, Sealra commented on frontend/src/routes/audits/edit/sections/AuditCustomFields.tsx
> +            : Math.round((1 / 12) * 100);
Es parte de la funcionalidad de los customFields, va fuera de este scope.

2024-10-14 01:43 UTC, Sealra commented on frontend/src/components/navbar/AuditSidebar.tsx
> +                {section.icon && section.icon.startsWith('fa-') ? (
Corregido

2024-10-14 01:43 UTC, Sealra commented on frontend/src/routes/audits/edit/AuditRoot.tsx
> +  }, []);
Esto puede ser un issue, prioricé la funcionalidad por tiempo.

2024-10-14 01:45 UTC, Sealra commented on frontend/src/services/audits.ts
> +};
Creo que es innecesario, además seria necesario agregar a todos los get que actualmente poseemos, dado que no lo realizamos en ninguno.

2024-10-14 01:46 UTC, Sealra commented on frontend/src/services/audits.ts
> +
Cositas de pwndoc, está bien el type.

2024-10-14 01:52 UTC, Sealra commented on frontend/src/services/audits.ts
> +};
Esto ta bien, cositas de pwndoc

2024-10-14 01:53 UTC, Sealra commented on frontend/src/routes/audits/edit/sections/sections.tsx
> +  const [dataAuditSection, setDataAuditSection] = useState<AuditSectionById>();
okas

2024-10-14 01:54 UTC, Sealra commented on frontend/src/routes/audits/edit/sections/sections.tsx
> +  const [dataAuditSection, setDataAuditSection] = useState<AuditSectionById>();
fixed

2024-10-14 01:58 UTC, Sealra commented on frontend/src/routes/audits/edit/sections/sections.tsx
> +    }
Esto se deberia manejar con toasts, como dije anteriormente un issue.

2024-10-14 01:59 UTC, Sealra commented on frontend/src/routes/audits/edit/sections/sections.tsx
> +  }, [auditId, sectionId]);
fixed

2024-10-14 01:59 UTC, Sealra commented on frontend/src/routes/audits/edit/AuditRoot.tsx
> +  }, []);
también, manejar con toast, issue.

2024-10-14 02:01 UTC, Sealra commented on frontend/src/components/navbar/AuditSidebar.tsx
> +                    )}
El ESLint recomienda que no, 

Unnecessary optional chain on a non-nullish value.

2024-10-14 02:03 UTC, Sealra commented on frontend/src/components/navbar/AuditSidebar.tsx
> +                  >
Como comenté anteriormente, esta lógica requiere modificaciones extensas al backend, se deberia discutir a fondo en una daily post sprint. De momento tal vez sea mejor retirar este botón y la lista.

2024-10-14 02:03 UTC, Sealra commented on frontend/src/routes/audits/edit/sections/sections.tsx
> +  }, [dataAuditSection, currentLanguage]);
Refactorización innecesaria para un caso específico creo yo.

2024-10-14 02:04 UTC, Sealra commented on frontend/src/routes/audits/edit/sections/sections.tsx
> +    });
Refactorización innecesaria para un caso específico creo yo.

2024-10-14 02:05 UTC, Sealra commented on frontend/src/routes/audits/edit/sections/sections.tsx
> +  }, [auditId, sectionId]);
Creo que esto seria mejor manejarlo con un toast, además me parece un caso raro, considerando el flujo del front.

2024-10-14 15:30 UTC, jllanosg commented
@Sealra resolver conflictos pls

2024-10-15 01:01 UTC, Sealra commented
> @Sealra resolver conflictos pls

listo 👍

2024-10-15 13:22 UTC, Sealra commented on frontend/src/routes/audits/edit/sections/sections.tsx
> +  }, [dataAuditSection, currentLanguage]);
No considero necesario convertir en una función un caso específico.

2024-10-15 13:23 UTC, Sealra commented on frontend/src/routes/audits/edit/sections/sections.tsx
> +    });
No considero necesario convertir en una función un caso específico.

2024-10-15 13:24 UTC, Sealra commented on frontend/src/components/navbar/AuditSidebar.tsx
> +          </div>
Acá como comentaba, solo cierra la lista porque no está implementada la funcionalidad de agregar customSection al audit, que requiere cambios al backend.

2024-10-15 13:25 UTC, Sealra commented on frontend/src/routes/audits/edit/AuditRoot.tsx
> +  }, []);
La aplicación de los toast queda pendiente como issue.

2024-10-15 13:25 UTC, Sealra commented on frontend/src/routes/audits/edit/AuditRoot.tsx
> +        setIsListVisible={setIsListVisible}
No sé si será necesario, actualmente funciona bien.

2024-10-15 13:26 UTC, Sealra commented on frontend/src/services/audits.ts
> +
Los tipos de customField varian para distintos endpoint, cositas de pwndoc

2024-10-15 13:28 UTC, Sealra commented on frontend/src/services/audits.ts
> +};
Comenté que esto requeriria una refactorización de las consultas al api, queda fuera del scope de este PR.

2024-10-15 14:17 UTC, Sealra commented
@caverav devolví la branch al commit pre-explotar por el merge, pls auxilio

2024-10-15 19:32 UTC, Sealra commented
> ![image](https://private-user-images.githubusercontent.com/66751764/376764030-9fee3fa6-034c-40b1-aa32-89f2d767e996.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwMjA2NTEsIm5iZiI6MTcyOTAyMDM1MSwicGF0aCI6Ii82Njc1MTc2NC8zNzY3NjQwMzAtOWZlZTNmYTYtMDM0Yy00MGIxLWFhMzItODlmMmQ3NjdlOTk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDE5MjU1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhNTIwNTMzMTk1N2NjZjRhZGUzNTYyY2M3ODM2ZTRhZTMzMDVmY2JhMmM0ZWIyMmQ4MzNiMmZhNWE5NzRkODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.yJwsfGeCrdfRP4oclZsV0Lh1Rn8nh7yl5Hc0fSrFow0) Al apretar en un custom section, no me aparece nada para editar

aplicaste el flujo mencionado en la descripción del pr? editar un audit type (o custom field) de un audit ya creado no modificará para ese audit (por como funciona el back de pwndoc)

2024-10-15 19:33 UTC, Sealra commented
> ![image](https://private-user-images.githubusercontent.com/66751764/376764499-625a5308-d9c2-45b0-836c-4fbd24737100.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwMjA2NTAsIm5iZiI6MTcyOTAyMDM1MCwicGF0aCI6Ii82Njc1MTc2NC8zNzY3NjQ0OTktNjI1YTUzMDgtZDljMi00NWIwLTgzNmMtNGZiZDI0NzM3MTAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDE5MjU1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2MzgxNDZiYTc4NWY2YmZlNWUyMmJhN2U3ZDA2ZmNjZjJiN2RlOGY0M2NiNGYzMzVmZmYwOTk2Y2I4ZTliNDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.EGZUtZA7GaKYsfJVV51hQkz2Tozzt43NUGyO9zv7b4o) En esta sección al apretar cualquier botón no sucede nada, cuál es la utilidad?

Esto lo comenté en algun comentario de codeRabbit, la funcionalidad de añadir directamente quedaría como issue (creo), porque requerirá modificaciones extensas al back, de momento pensaba en probablemente comentar o eliminar para este sprint esa funcionalidad.

2024-10-15 19:36 UTC, caverav commented
> > ![image](https://private-user-images.githubusercontent.com/66751764/376764030-9fee3fa6-034c-40b1-aa32-89f2d767e996.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwMjA2NTEsIm5iZiI6MTcyOTAyMDM1MSwicGF0aCI6Ii82Njc1MTc2NC8zNzY3NjQwMzAtOWZlZTNmYTYtMDM0Yy00MGIxLWFhMzItODlmMmQ3NjdlOTk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDE5MjU1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhNTIwNTMzMTk1N2NjZjRhZGUzNTYyY2M3ODM2ZTRhZTMzMDVmY2JhMmM0ZWIyMmQ4MzNiMmZhNWE5NzRkODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.yJwsfGeCrdfRP4oclZsV0Lh1Rn8nh7yl5Hc0fSrFow0) Al apretar en un custom section, no me aparece nada para editar
> 
> aplicaste el flujo mencionado en la descripción del pr? editar un audit type (o custom field) de un audit ya creado no modificará para ese audit (por como funciona el back de pwndoc)

Yep

2024-10-15 20:07 UTC, Sealra commented
> > > ![image](https://private-user-images.githubusercontent.com/66751764/376764030-9fee3fa6-034c-40b1-aa32-89f2d767e996.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwMjA2NTEsIm5iZiI6MTcyOTAyMDM1MSwicGF0aCI6Ii82Njc1MTc2NC8zNzY3NjQwMzAtOWZlZTNmYTYtMDM0Yy00MGIxLWFhMzItODlmMmQ3NjdlOTk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDE5MjU1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhNTIwNTMzMTk1N2NjZjRhZGUzNTYyY2M3ODM2ZTRhZTMzMDVmY2JhMmM0ZWIyMmQ4MzNiMmZhNWE5NzRkODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.yJwsfGeCrdfRP4oclZsV0Lh1Rn8nh7yl5Hc0fSrFow0) Al apretar en un custom section, no me aparece nada para editar
> > 
> > 
> > aplicaste el flujo mencionado en la descripción del pr? editar un audit type (o custom field) de un audit ya creado no modificará para ese audit (por como funciona el back de pwndoc)
> 
> Yep

![image](https://github.com/user-attachments/assets/5ee39ba1-9942-4245-9e91-a29d6febe20e)

no me pasa, podríamos verificar tu flujo por discord

2024-10-15 20:40 UTC, caverav commented
> > > > ![image](https://private-user-images.githubusercontent.com/66751764/376764030-9fee3fa6-034c-40b1-aa32-89f2d767e996.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwMjA2NTEsIm5iZiI6MTcyOTAyMDM1MSwicGF0aCI6Ii82Njc1MTc2NC8zNzY3NjQwMzAtOWZlZTNmYTYtMDM0Yy00MGIxLWFhMzItODlmMmQ3NjdlOTk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDE5MjU1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhNTIwNTMzMTk1N2NjZjRhZGUzNTYyY2M3ODM2ZTRhZTMzMDVmY2JhMmM0ZWIyMmQ4MzNiMmZhNWE5NzRkODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.yJwsfGeCrdfRP4oclZsV0Lh1Rn8nh7yl5Hc0fSrFow0) Al apretar en un custom section, no me aparece nada para editar
> > > 
> > > 
> > > aplicaste el flujo mencionado en la descripción del pr? editar un audit type (o custom field) de un audit ya creado no modificará para ese audit (por como funciona el back de pwndoc)
> > 
> > 
> > Yep
> 
> ![image](https://private-user-images.githubusercontent.com/71726988/376783779-5ee39ba1-9942-4245-9e91-a29d6febe20e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwMjUwMDMsIm5iZiI6MTcyOTAyNDcwMywicGF0aCI6Ii83MTcyNjk4OC8zNzY3ODM3NzktNWVlMzliYTEtOTk0Mi00MjQ1LTllOTEtYTI5ZDZmZWJlMjBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDIwMzgyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkMGJmZDFiY2UwMDM5ZGM2YzBiNWE4NDdmM2RlZTNmNTEyNzk1ZTJiMDNiNzUyZWEyZTU0MTFkY2MzNGQ0NDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qex6fgcREqC7HX2Aaxh-R-S5N0fhPZzg8RcNc5gqXMM)
> 
> no me pasa, podríamos verificar tu flujo por discord

Era que por defecto se encuentra así:
![image](https://github.com/user-attachments/assets/0e505f75-d0d3-47f3-b46e-58c715d7fc22)
Faltó indicar que hay que seleccionar Audit Section, lo agregaré yo al PR, con eso me funcionó bien

2024-10-16 13:51 UTC, iTzGooDLife requested changes
Falta resolver los conflictos con development.

2024-10-16 15:46 UTC, Sealra commented
> Falta resolver los conflictos con development.

fueron resueltos 👍

2024-10-16 19:38 UTC, Sealra commented on frontend/src/components/navbar/AuditSidebar.tsx
> +                      )}
podria aplicarse como lógica en un issue, pero lo veo innecesario por el tiempo restante

2024-10-16 23:28 UTC, iTzGooDLife approved these changes
APRUEBO!

2024-10-16 23:28 UTC, merged